### PR TITLE
Clean up config file for Travis.

### PR DESCRIPTION
**Pull request by jugmac00**
- remove obsolete "sudo" keyword
- remove old dev versions
- remove matrix

modified:   .travis.yml

P.S.: As I never used the "allow_failures" directive before, I am not sure whether I used the correct syntax (outside matrix). If not, I'll update the pr.

### CODE REVIEW

**Comment by jugmac00** [comment]
Hm... the PR triggered no build on Travis. 

@tylerwince Could you please activate Travis builds for PRs? Thank you!

**Comment by tylerwince** [comment]
@jugmac00 thanks for this PR! The travis builds are supposed to be running for PRs... let me take a look and see if I can force run it.

**Comment by jugmac00** [comment]
Thx @tylerwince for getting back to me!

I fixed the Travis config file. Apparently, you have to put the **allow_failures** directive within a **matrix block**. Neat, I learned something new :-)

**Comment by tylerwince** [comment]
Thanks @jugmac00

**Pull request merged**
